### ISSUE TITLE
Initialize Android Project

### ISSUE THREAD

**Issue by ryuuzake** [agustinanisaf/SquareCheck-android#1]
Inisialisasi Project Android
===

Requirements / Library
---
- [x] AndroidX
- [x] Gson
- [x] Retrofit

Add to build.gradle (:app)
---
- [x] minSdkVersion  21
- [x] targetSdkVersion 30

*_kalau ada tanda kuning, update dulu ke versi paling baru baru push_
- [x] implementation 'androidx.appcompat:appcompat:1.1.0'
- [x] implementation 'androidx.recyclerview:recyclerview:1.1.0'
- [x] implementation 'androidx.constraintlayout:constraintlayout:2.0.3'
- [x] implementation 'com.google.code.gson:gson:2.8.5'
- [x] implementation 'com.squareup.retrofit2:retrofit:2.9.0'
- [x] implementation "com.squareup.retrofit2:converter-gson:2.9.0"
- [x] implementation 'com.squareup.okhttp3:logging-interceptor:4.2.1'

**Comment by AanMFA** [comment]
nambahi resource" dasar koyok warna", icon aplikasi dkk gak dilebokne kene pisan?

**Comment by ryuuzake** [comment]
@AanMFA gak wes, dibuat issue nyar ae, ben isok diedit barengan sek ae
