### ISSUE TITLE
Create Android Application Logo

### ISSUE THREAD

**Issue by ryuuzake** [agustinanisaf/SquareCheck-android#15]
Create Android Application Logo from Original Illustrator File

**Comment by ryuuzake** [comment]
@rizabach29 nak branchku wes tak buatno, lek menurutmu kurang pas iku bok tambahi.  
Mungkin kon apene nambah tulisan Square Check nak dalem Logone

**Comment by rizabach29** [comment]
okeokee, aku iki sek mbenakno web
