### ISSUE TITLE
Create Model from API Data

### ISSUE THREAD

**Issue by ryuuzake** [agustinanisaf/SquareCheck-android#22]
What to do
---
- [x] List API Data yang dibutuhkan oleh Android
- [x] Buat Model menggunakan [jsonschema2pojo.org](http://www.jsonschema2pojo.org/)

References
---
- [Square Check API Postman](https://documenter.getpostman.com/view/8289361/TVRn47ch)
- Cara Menggunakan JSONSchema2POJO

1. Masukkan hasil response dari API ke Jsonschema2pojo.org
![image](https://user-images.githubusercontent.com/31271087/99608178-f5cb9c00-2a3f-11eb-82e0-56c253c0ff2e.png)

2. Klik Preview > Lalu copy - paste menjadi class baru di Android Studio
![image](https://user-images.githubusercontent.com/31271087/99608354-493dea00-2a40-11eb-8e59-34947427741d.png)

*_Jangan langsung merge, dicheck dulu sama system ada error apa enggak_

**Comment by rizabach29** [comment]
@ryuuzake mohon dibantu ya kalo ada kesulitan saya

**Comment by ryuuzake** [comment]
yoai, sakjane apene tak detail lagi iki, soale terlalu gede task e, jadi mungkin isok dipecah2

**Comment by rizabach29** [comment]
aku ngerjakno sing endi iki?

**Comment by ryuuzake** [comment]
ambil beberapa model yang belum dibuat, koyok subject, schedule, dll.

**Comment by ryuuzake** [comment]
Another Commit 27c06de
