### ISSUE TITLE
Fix Both User's Toolbar

### ISSUE THREAD

**Issue by ryuuzake** [agustinanisaf/SquareCheck-android#54]
What to do
---

- [x] Show profile of the lecturer
- [x] Fix position of profile layout inside toolbar
- [x] Hide the back button while using dashboard view
- [x] Map all interaction to respective method
- [x] Show default profile image based on XD

References
---

1. Lecturer Toolbar Menu == Student Toolbar Menu

*_Jangan langsung merge, dicheck dulu sama system ada error apa enggak_

**Comment by AanMFA** [comment]
branch sudah terpush salah commit message bagian nomer issue
